# Generated by Django 4.2.11 on 2025-03-18 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_licence',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='driving_licence_expire_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('IAC', 'InActive'), ('BL', 'Black List')], default='AC', max_length=3),
        ),
    ]
