# Generated by Django 4.2.11 on 2025-03-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birthdate_user_driving_licence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driving_licence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driving_licence_expire_Date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
