# Generated by Django 4.2.11 on 2025-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=355)),
                ('status', models.BooleanField(default=True)),
                ('year_of_construction', models.DateField(default=None, null=True)),
                ('total_area', models.FloatField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('google_map_link', models.CharField(blank=True, max_length=255, null=True)),
                ('yandex_map_link', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
    ]
