# Generated by Django 5.2 on 2025-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_car_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
